# Generated by Django 3.2.11 on 2022-01-08 06:44

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220108_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_items', to='blog.blogpage'),
        ),
    ]
